/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.helper.CadastroHelper;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Compaq
 */
public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastro = new javax.swing.JLabel();
        jLabelApelido = new javax.swing.JLabel();
        jFieldApelido = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jFieldSenha = new javax.swing.JPasswordField();
        jLinkLogin = new javax.swing.JLabel();
        jBtnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCadastro.setText("Cadastro de Usuário");
        getContentPane().add(jLabelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabelApelido.setText("Apelido");
        getContentPane().add(jLabelApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(jFieldApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 250, -1));

        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, -1));

        jLinkLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLinkLogin.setText("Já é cadastrado?");
        jLinkLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLinkLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLinkLoginMousePressed(evt);
            }
        });
        getContentPane().add(jLinkLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jBtnCadastrar.setText("CADASTRAR");
        jBtnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCadastrarMousePressed(evt);
            }
        });
        getContentPane().add(jBtnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldSenhaActionPerformed

    private void jLinkLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLinkLoginMousePressed
        login view = new login();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLinkLoginMousePressed

    private void jBtnCadastrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadastrarMousePressed
        CadastroHelper helper = new CadastroHelper(this);
        helper.cadastrar();
    }//GEN-LAST:event_jBtnCadastrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JTextField jFieldApelido;
    private javax.swing.JPasswordField jFieldSenha;
    private javax.swing.JLabel jLabelApelido;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLinkLogin;
    // End of variables declaration//GEN-END:variables

    
    public JTextField getjFieldApelido() {
        return jFieldApelido;
    }

    public JPasswordField getjFieldSenha() {
        return jFieldSenha;
    }

    
}
