/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JPasswordField;
import javax.swing.JTextField;
import controller.helper.LoginHelper;

/**
 *
 * @author Compaq
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        jLabelApelido = new javax.swing.JLabel();
        jFieldApelido = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jFieldSenha = new javax.swing.JPasswordField();
        jLinkCadastro = new javax.swing.JLabel();
        jBtnLogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelLogin.setText("LOGIN");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabelApelido.setText("Apelido");
        getContentPane().add(jLabelApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jFieldApelido.setToolTipText("Apelido");
        getContentPane().add(jFieldApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 229, -1));

        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jFieldSenha.setToolTipText("Senha");
        getContentPane().add(jFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 230, -1));

        jLinkCadastro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLinkCadastro.setText("Ainda não está cadastrado?");
        jLinkCadastro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLinkCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLinkCadastroMousePressed(evt);
            }
        });
        getContentPane().add(jLinkCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 170, 20));

        jBtnLogar.setText("LOGAR");
        jBtnLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLogarMousePressed(evt);
            }
        });
        getContentPane().add(jBtnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 97, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLogarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLogarMousePressed
        LoginHelper helper = new LoginHelper(this);        
        helper.logar();
    }//GEN-LAST:event_jBtnLogarMousePressed

    private void jLinkCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLinkCadastroMousePressed
        cadastro view = new cadastro();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLinkCadastroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogar;
    private javax.swing.JTextField jFieldApelido;
    private javax.swing.JPasswordField jFieldSenha;
    private javax.swing.JLabel jLabelApelido;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLinkCadastro;
    // End of variables declaration//GEN-END:variables

    public JTextField getjFieldApelido() {
        return jFieldApelido;
    }

    public JPasswordField getjFieldSenha() {
        return jFieldSenha;
    }

    

}
