/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.dao.CampoDao;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.bean.CampoInfo;
import model.conn.ConnectionFactory;

/**
 *
 * @author telva
 */
public class novoCampo extends javax.swing.JFrame {
    private Long ID = null;
    private Formulario form;
    /**
     * Creates new form novoCampo
     */
    public novoCampo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jFieldTitulo = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelObrigatorio = new javax.swing.JLabel();
        jCBObrigatorio = new javax.swing.JCheckBox();
        jComboTipo = new javax.swing.JComboBox<>();
        jBtnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Campo");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setText("Titulo");

        jFieldTitulo.setToolTipText("");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDescricao.setText("Descrição");

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setText("Tipo");

        jLabelObrigatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelObrigatorio.setText("Será obrigatório?");

        jCBObrigatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCBObrigatorio.setText("Sim");
        jCBObrigatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBObrigatorioActionPerformed(evt);
            }
        });

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Numérico" }));
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });

        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRegistrarMouseClicked(evt);
            }
        });

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelObrigatorio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCBObrigatorio))
                        .addComponent(jLabelDescricao)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTitulo))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTipo)
                                .addComponent(jComboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelTipo))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabelDescricao)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelObrigatorio)
                    .addComponent(jCBObrigatorio))
                .addGap(30, 30, 30)
                .addComponent(jBtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoActionPerformed

    private void jCBObrigatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBObrigatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBObrigatorioActionPerformed

    private void jBtnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistrarMouseClicked
        String titulo = getjFieldTitulo().getText();
        String tipo = getjComboTipo().getSelectedItem().toString();
        String descricao = getjTextAreaDesc().getText();
        boolean eobrigatorio = getjCBObrigatorio().isSelected();
        
        if( !(titulo.isEmpty() || tipo.isEmpty() ) ) {
            String msgTexto = "";
            String msgTitulo = "";
            CampoDao dao = new CampoDao(new ConnectionFactory().getConnection());
            CampoInfo campo = new CampoInfo(
                    titulo,
                    descricao.isEmpty() ? null : descricao,
                    tipo.toLowerCase(),
                    1,
                    eobrigatorio
            );
            
            // Criar
            if(ID == null) {
                ID = dao.create(campo);
                if(ID!=null) msgTexto = "Concluído o registro do novo campo " + titulo + ". Deseja voltar ao formulário?";
                msgTitulo = "Registro de Novo Campo";
            } else {
                campo.setID(ID);
                dao.atualizar(campo);
                
                msgTexto = "Concluído a atualização de " + titulo + ". Deseja voltar ao formulário?";
                msgTitulo = "Atualização de Campo";
            }
            
            if(ID != null) {
                int opt = JOptionPane.showConfirmDialog(this, msgTexto, msgTitulo, JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                if(opt == JOptionPane.YES_OPTION) {
                    form.setLayoutItens();
                    dispose();
                } 
            } else {
                JOptionPane.showMessageDialog(this, "Erro de Inserção");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
        }
    }//GEN-LAST:event_jBtnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novoCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novoCampo().setVisible(true);
            }
        });
    }

    public JCheckBox getjCBObrigatorio() {
        return jCBObrigatorio;
    }

    public void setjCBObrigatorio(JCheckBox jCBObrigatorio) {
        this.jCBObrigatorio = jCBObrigatorio;
    }

    public JComboBox<String> getjComboTipo() {
        return jComboTipo;
    }

    public void setjComboTipo(JComboBox<String> jComboTipo) {
        this.jComboTipo = jComboTipo;
    }

    public JTextField getjFieldTitulo() {
        return jFieldTitulo;
    }

    public void setjFieldTitulo(JTextField jFieldTitulo) {
        this.jFieldTitulo = jFieldTitulo;
    }

    public JTextArea getjTextAreaDesc() {
        return jTextAreaDesc;
    }

    public void setjTextAreaDesc(JTextArea jTextAreaDesc) {
        this.jTextAreaDesc = jTextAreaDesc;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JCheckBox jCBObrigatorio;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JTextField jFieldTitulo;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelObrigatorio;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDesc;
    // End of variables declaration//GEN-END:variables

    void setForm(Formulario form) {
        this.form = form;
    }
}
